In [511]:
import numpy as np
import numpy.linalg as la
import math

In [512]:
inp_eqn = input()
# inp_eqn = 'H 2 + O 2 = H 2 O'
# inp_eqn = 'N 2 + H 2 = N H 3'
inp_eqn = 'H 2 O + S O 2 = H 2 S O 4'
# inp_eqn = 'Na Cl + Ag N O 3 = Na N O 3 + Ag Cl'

In [513]:
def balance_chemical_eqation(inp_eqn):
    sub_dict = {}
    alphabets = "abcdefghijklmonpqrstuvwxyz"
    for mols in inp_eqn.split():
        if len(mols) > 1 and mols.isalpha():
            sub_dict[alphabets[0]] = mols
            inp_eqn = inp_eqn.replace(mols, alphabets[0])
            alphabets = alphabets[1:]
    inp = ''.join(inp_eqn.split())
    inp = inp.split('=')
    react = inp[0]
    prod = inp[1]

    atom_list = []

    for letter in react:
        if letter.isalpha() and letter not in atom_list:
            atom_list.append(letter)

    react = react.split('+')
    prod = prod.split('+')

    if type(react) == str:
        react = [react]

    if type(prod) == str:
        prod = [prod]

    # print(react, prod, atom_list)

    coeffs = []

    for mol in react:
        # mol_cf = np.zeros(len(atom_list))
        mol_cf = [0] * len(atom_list)
        for i in range(len(mol)):
            char = mol[i]
            if char in atom_list and i != (len(mol) - 1) and mol[i+1].isalpha() == False:
                mol_cf[atom_list.index(char)] += float(mol[i+1])
            elif char in atom_list:
                mol_cf[atom_list.index(char)] += 1
        coeffs.append(mol_cf)

    for mol in prod:
        # mol_cf = np.zeros(len(atom_list))
        mol_cf = [0] * len(atom_list)
        # print(mol_cf)
        for i in range(len(mol)):
            char = mol[i]
            if char in atom_list and i != (len(mol) - 1) and mol[i+1].isalpha() == False:
                mol_cf[atom_list.index(char)] -= float(mol[i+1])
            elif char in atom_list:
                mol_cf[atom_list.index(char)] -= 1
        coeffs.append(mol_cf)
        
    if len(coeffs) > len(coeffs[0]):
        diff = (len(coeffs) - len(coeffs[0]))
        for row in coeffs:
            for i in range(diff):
                row.append(0)
    elif len(coeffs) < len(coeffs[0]):
        diff = (len(coeffs[0]) - len(coeffs))
        for i in range(diff):
            coeffs.append([0] * len(coeffs[0]))

    coeffs = np.array(np.transpose(coeffs))

    vals, vecs = la.eig(coeffs)
    vecs = np.transpose(vecs)
    ans = np.where(abs(vals) < 1e-9)[0][0]
    req_vec = vecs[ans].real

    my_primes = [2, 3, 5, 7, 11, 13, 17, 19]
    for i in range(len(req_vec)):
        for p in my_primes:
            req_vec[i] *= p

    my_gcd = int(req_vec[0])
    print(req_vec)
    for v in req_vec:
        my_gcd = math.gcd(int(v), my_gcd)

    req_vec = np.array(req_vec)

    req_vec /= my_gcd

    for i in range(len(react)):
        react[i] = str(round(req_vec[i])) + react[i]
        react[i] = " ".join(react[i])

    for i in range(len(prod)):
        prod[i] = str(round(req_vec[len(react) + i])) + prod[i]
        prod[i] = " ".join(prod[i])

    react_str = " + ".join(react)
    prod_str = " + ".join(prod)
    output_eqn = react_str + " = " + prod_str
    final_eq = ""
    for letter in output_eqn:
        if letter in sub_dict.keys():
            final_eq += sub_dict[letter]
        else:
            final_eq += letter

    return final_eq

In [514]:
sub_dict = {}
alphabets = "abcdefghijklmonpqrstuvwxyz"
for mols in inp_eqn.split():
    if len(mols) > 1 and mols.isalpha():
        sub_dict[alphabets[0]] = mols
        inp_eqn = inp_eqn.replace(mols, alphabets[0])
        alphabets = alphabets[1:]
inp = ''.join(inp_eqn.split())
inp = inp.split('=')
react = inp[0]
prod = inp[1]

atom_list = []

for letter in react:
    if letter.isalpha() and letter not in atom_list:
        atom_list.append(letter)

react = react.split('+')
prod = prod.split('+')

if type(react) == str:
    react = [react]

if type(prod) == str:
    prod = [prod]

# print(react, prod, atom_list)

coeffs = []

for mol in react:
    # mol_cf = np.zeros(len(atom_list))
    mol_cf = [0] * len(atom_list)
    for i in range(len(mol)):
        char = mol[i]
        if char in atom_list and i != (len(mol) - 1) and mol[i+1].isalpha() == False:
            mol_cf[atom_list.index(char)] += float(mol[i+1])
        elif char in atom_list:
            mol_cf[atom_list.index(char)] += 1
    coeffs.append(mol_cf)

for mol in prod:
    # mol_cf = np.zeros(len(atom_list))
    mol_cf = [0] * len(atom_list)
    # print(mol_cf)
    for i in range(len(mol)):
        char = mol[i]
        if char in atom_list and i != (len(mol) - 1) and mol[i+1].isalpha() == False:
            mol_cf[atom_list.index(char)] -= float(mol[i+1])
        elif char in atom_list:
            mol_cf[atom_list.index(char)] -= 1
    coeffs.append(mol_cf)

# coeffs = np.array(coeffs)

coeffs

[[2.0, 1, 0], [0, 2.0, 1], [-2.0, -4.0, -1]]

In [515]:
if len(coeffs) > len(coeffs[0]):
    diff = (len(coeffs) - len(coeffs[0]))
    for row in coeffs:
        for i in range(diff):
            row.append(0)
elif len(coeffs) < len(coeffs[0]):
    diff = (len(coeffs[0]) - len(coeffs))
    for i in range(diff):
        coeffs.append([0] * len(coeffs[0]))
        

In [516]:
coeffs = np.array(np.transpose(coeffs))
# coeffs = np.array(coeffs)

In [517]:
coeffs

array([[ 2.,  0., -2.],
       [ 1.,  2., -4.],
       [ 0.,  1., -1.]])

In [518]:
print(la.eig(coeffs))
vals, vecs = la.eig(coeffs)
vecs = np.transpose(vecs)
ans = np.where(abs(vals.real) < 1e-9)[0][0]
req_vec = vecs[ans].real
# vecs
# print(vecs)
# la.eig()

(array([1.+0.j, 1.+1.j, 1.-1.j]), array([[ 0.66666667+0.j        , -0.47434165-0.15811388j,
        -0.47434165+0.15811388j],
       [ 0.66666667+0.j        , -0.79056942+0.j        ,
        -0.79056942-0.j        ],
       [ 0.33333333+0.j        , -0.31622777+0.15811388j,
        -0.31622777-0.15811388j]]))


IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
print(req_vec)
my_primes = [2, 3, 5, 7, 11, 13, 17, 19]
for i in range(len(req_vec)):
    for p in my_primes:
        req_vec[i] *= p

my_gcd = int(req_vec[0])
print(req_vec)
for v in req_vec:
    my_gcd = math.gcd(int(v), my_gcd)

req_vec = np.array(req_vec)

req_vec /= my_gcd

[0.26726124 0.80178373 0.53452248]
[2592351.19556552 7777053.58669657 5184702.39113105]


In [ ]:
print(req_vec)

for i in range(len(react)):
    react[i] = str(round(req_vec[i])) + react[i]
    react[i] = " ".join(react[i])

for i in range(len(prod)):
    prod[i] = str(round(req_vec[len(react) + i])) + prod[i]
    prod[i] = " ".join(prod[i])

[1.00000008 3.00000023 2.00000015]


In [ ]:
print(react, prod)
react_str = " + ".join(react)
prod_str = " + ".join(prod)
output_eqn = react_str + " = " + prod_str
final_eq = ""
for letter in output_eqn:
    if letter in sub_dict.keys():
        final_eq += sub_dict[letter]
    else:
        final_eq += letter

['1 N 2', '3 H 2'] ['2 N H 3']


In [ ]:
print(final_eq)

1 N 2 + 3 H 2 = 2 N H 3


In [ ]:
round(3.9)

4